### ISSUE TITLE
Include EPSG:23700

### ISSUE THREAD

**Issue by davids91** [OSGeo/PROJ-data#103]
https://epsg.io/23700 would be a great and useful addition to the database!

**Comment by jjimenezshaw** [comment]
It is there:
https://crs-explorer.proj.org/?searchText=23700&ignoreWorld=false&allowDeprecated=false&authorities=EPSG&activeTypes=PROJECTED_CRS

What is the problem?

**Comment by jjimenezshaw** [comment]
> Sorry I didn't seem to find it on: https://cdn.proj.org/

PROJ-data (https://github.com/OSGeo/PROJ-data/) is about grid (transformation) files, not about coordinate reference systems.
See that those grid files must be open source with a proper license.
If you think there is any needed grid file, follow the steps in PROJ-data to add it via a PR.

**Comment by rouault** [comment]
There's actually a pending pull request at https://github.com/OSGeo/PROJ-data/pull/68 about a grid for HD72 but we didn't manage to make a conclusion with the submitter and other parties knowledgeable of Hungarian datum

Closing that ticket as I don't think there's anything to do here, until https://github.com/OSGeo/PROJ-data/pull/68 has progressed
