### ISSUE TITLE
Add GCG2016 geoid to support DHHN2016

### ISSUE THREAD

**Issue by ktheijs** [OSGeo/PROJ-data#107]
Since June 1 2023 BKG seems to have made GCG2016 publicly available. Does that mean that it can now be added to the CDN?

You can find the data and all information here: https://gdz.bkg.bund.de/index.php/default/digitale-geodaten/geodaetische-basisdaten/quasigeoid-der-bundesrepublik-deutschland-quasigeoid.html

It would be great to have support for DHHN2016.

**Comment by kbevers** [comment]
It seems to be put under a CC-BY 4.0 license, so yes, it should be possible to add it the this repo.

**Comment by jjimenezshaw** [comment]
I can add it, I have part of the work done.

**Comment by jjimenezshaw** [comment]
We already have a Federal organization for Germany in PROJ-data: AdV "Arbeitsgemeinschaft der Vermessungsverwaltungen der Länder der Bundesrepublik Deutschland" (https://www.adv-online.de/)
The geoid model is published by BKG "Bundesamt für Kartographie und Geodäsie" (https://www.bkg.bund.de/)

I do not know exactly the difference between these two organisms. I think they work together.

Should I create a new folder `de_bkg`, or can I use `de_adv`?

PS there are more folders for some different "Bundesländer"

**Comment by rouault** [comment]
I would go for de_bkg as the link to the geoid is there and the EPSG record for the transformation also lists BKG as the source

**Comment by jjimenezshaw** [comment]
Good point about EPSG. I will go with it.

The other grid (DHDN to ETRS89) in EPSG is also mentioning BKG https://epsg.org/transformation_15948/DHDN-to-ETRS89-8.html 

Here BKG is talking about the geoid model... from AdV
https://www.bkg.bund.de/SharedDocs/Downloads/BKG/DE/Downloads-DE-Flyer/BKG-Quasigeoid-DE.pdf?__blob=publicationFile&v=11
That starts with "Die Höhenbezugsfläche der Arbeitsgemeinschaft der Vermessungsverwaltungen der Länder (AdV)" (The height reference surface of the Association of Surveying Administrations of the States (AdV))
It is not really clear to me.

uhmmm, it was bkg in the past, and changed at https://github.com/OSGeo/PROJ-data/commit/c9656138fa51fbc0bc341e4069f903ca91879754 Do you remember why was it changed @rouault ?

Sorry for asking, but I guess that changing the folder and file names later is going to be a mess. Better knowing it in advance.

**Comment by rouault** [comment]
> Do you remember why was it changed @rouault ?

my memories about that have unfortunately vanished. My assumption would be that the link from BKG lead to ADV as the actual downloading site, hence I assumed ADV was better.
Given the unclear situation , up to you if you want to put in de_adv or de_bkg
