### ISSUE TITLE
Create release packages using GitHub Actions

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ-data#122]
Generating the zip and tar.gz files for the PROJ-data releases have proven to be unreliable on the Mac that I am currently using when preparing new releases. Both releases in the 9.4 series have been affected and included unwanted ._-files. To prevent this in the future a new workflow based on GitHub Actions will be investigated. 

Ideally, a pushed git tag will trigger creation of the release packages and store them as artifacts attached to given workflow run. This would mean that when a tag such as `1.18.0RC1` is pushed a workflow will be triggered that creates `PROJ-data-1.18RC1.tar.gz` and `PROJ-data-1.18RC1.zip` and stores them as downloadable artifacts. Upload to download.osgeo.org will be a manual process as previously.

**Comment by sebastic** [comment]
It might be simpler to remove the extended attributes from any files in the working directory as part of the release process, e.g.:
```
find . -type f -exec xattr -c {} \;
```

**Comment by mwtoews** [comment]
I've been thinking of a similar strategy too. The libgeos team have [a release.yml workflow](https://github.com/libgeos/geos/blob/main/.github/workflows/release.yml) as inspiration. And now their md5sum from (e.g) [geos-3.12.1.tar.bz2](https://github.com/libgeos/geos/releases/download/3.12.1/geos-3.12.1.tar.bz2) at https://github.com/libgeos/geos/releases/tag/3.12.1 is identical to the one at https://download.osgeo.org/geos/ which is neat. This idea applies to PROJ too.

**Comment by hobu** [comment]
I implemented automated release artifact generation (and signing!) using GitHub Actions in libgeotiff recently. This could be adapted to PROJ/PROJ-data without much trouble.
