### ISSUE TITLE
Add grids for Slovakia

### ISSUE THREAD

**Issue by wonder-sk** [OSGeo/PROJ-data#15]
I have received a confirmation from Slovak geodetic authorities that the grids are now licensed under the terms of CC-BY-ND 4.0. Here is the link for downloads:
https://www.geoportal.sk/en/geodeticke-zaklady/download/

Available grids:
- jtsk03_to_jtsk (horizontal)
- etrs89h_to_evrf2007 (vertical)
- etrs89h_to_baltic1957 (vertical)

From the description of CC-BY-ND license I understand that "NoDerivative" clause does not prohibit us from doing the conversion to GeoTIFF. It would be good if anyone can confirm -

**Comment by rouault** [comment]
>  I understand that "NoDerivative" clause does not prohibit us from doing the conversion to GeoTIFF.

From https://creativecommons.org/faq/#can-i-take-a-cc-licensed-work-and-use-it-in-a-different-format apparently yes, so this is a good news
@sebastic Would a CC-BY-ND 4.0 file be acceptable for Debian for a package in the standard repositories ?

**Comment by sebastic** [comment]
No, CC-BY-ND violates [DFSG #3](https://www.debian.org/social_contract#guidelines) making it non-free:
> **3. Derived Works**
> 
> The license must allow modifications and derived works, and must allow them to be distributed under the same terms as the license of the original software.

The same goes for the [OSD](https://opensource.org/osd-annotated).

Refer to the [The DFSG and Software Licenses](https://wiki.debian.org/DFSGLicenses) wiki for a list of known compatible and incompatible licenses.

**Comment by wonder-sk** [comment]
Where does that leave us - would be CC-BY-ND 4.0 acceptable for distribution by the PROJ, just would not be accepted in an official Debian package? Or does it mean that PROJ community would be also hesitant to include such grids in the online distribution system?

**Comment by sebastic** [comment]
The grids is not suitable for inclusion in PROJ-data, the README documents this:
> All grids in the package are released under permissive licenses. New grids are accepted into the package as long as they are released under a license that is compatible with the Open Source Definition and the source of the grid is clearly stated and verifiable.

CC-BY-ND is not compatible with the Open Source Definition.

**Comment by kbevers** [comment]
> Or does it mean that PROJ community would be also hesitant to include such grids in the online distribution system?

That is a good question. As we are registrering the specific licensing and copyright info for each grid we *could* include these grids in the package and let the Debian guys distribute only a subset of that. That would probably be a pain in the ass for @sebastic and likely other parties as well. That could be solved by releasing a "non-free" package and a "free" (well, Debian-approved) package. I don't know if that would be a good solution or if we should stick to only including grids live up to the Debian licensing requirements.

**Comment by sebastic** [comment]
It is appropriate to limit the grids included alongside PROJ to those that are open source just like PROJ.

**Comment by rouault** [comment]
@wonder-sk  What about extra advocating to the grid producer ? You could point them to https://cdn.proj.org/ to show that 23 geodetic agencies through the world have chosen licensing terms compatible of the open source definition. Couldn't they just opt for CC-BY 4.0 (no ND) as done by many other agencies ?

**Comment by wonder-sk** [comment]
Yeah I will try to advocate for that... As you probably know these government agencies often need to go through several levels of approvals, so it might take few months until we hear anything back. We will see.

**Comment by wonder-sk** [comment]
Good news - the agency has decided to change the license to CC-BY 4.0 :tada: 

The website contains the updated license information now:
https://www.geoportal.sk/en/geodeticke-zaklady/download/
