### ISSUE TITLE
North American 2022 Datums

### ISSUE THREAD

**Issue by mccarthyryanc** [OSGeo/PROJ-data#20]
I recently started reading about the new [North American datums](https://www.ngs.noaa.gov/datums/newdatums/index.shtml) being prepared by NOAA. This might be a naive question, but are these datums already in PROJ, or are they planned for a future release?

**Comment by kbevers** [comment]
As you say, the new datums are *being prepared* and is thus not ready yet. Hence they are of course not available in PROJ either. It is hard to say if and when they will land in PROJ. As far as I am aware the datums are somewhat differently designed than normal practice so they might not fit in PROJ without extra development. If that is the case, it all comes down to whether someone is willing to do it or can provide the necessary funding for it. If it is important to you I suggest you start thinking about how you can support such efforts.

**Comment by mccarthyryanc** [comment]
@kbevers Thanks for the explanation and I completely understand your comments about funding/support. I'll keep my eye on this and help where I can.

**Comment by rouault** [comment]
From my reading of the NOAA Blueprints, there are several areas where work will probably be needed in PROJ:
- the time-dependent relationship between NATRF2022 and ITRF will be through a Euler pole rotation. Not completely clear if this will be directly implementable through our existing 14-parameter Helmert transformation
- there will be time-dependent geoid models
- unclear yet how intra-plate deformation models will be conveyed
