### ISSUE TITLE
Missing plain text based EPSG specs defined in /usr/share/proj/epsg

### ISSUE THREAD

**Issue by bigopensky** [OSGeo/PROJ-data#57]
Where has  the file /usr/share/proj/epsg  gone. Best regards bigopensky

**Comment by kbevers** [comment]
It was removed with PROJ 6.0.0 in favour of `proj.db` database. It was never part of this repository.

**Comment by bigopensky** [comment]
Are there specifications for proj.db location, data format etc?

**Comment by kbevers** [comment]
Usually `proj.db` would be where you would find the `epsg` file. It's an SQLite file but don't go looking directly in the file, use `projinfo` to query the database. More on that here: https://proj.org/apps/projinfo.html
