### ISSUE TITLE
Failing Docker image due to SHA256 mismatch on 'no_kv_README.txt' with 'pyproj sync --all' step

### ISSUE THREAD

**Issue by sunayana** [OSGeo/PROJ-data#91]
Could some one help us out with the error, the description of the issue can be found in the link below.
https://github.com/pyproj4/pyproj/issues/1226
We were asked to open the issue here.

**Comment by rouault** [comment]
https://cdn.proj.org/files.geojson updated with the correct sha256sum

**Comment by sunayana** [comment]
Thanks a lot @rouault
