### ISSUE TITLE
PROJ 6 request - OSGM15_GB.gtx

### ISSUE THREAD

**Issue by OrangeDog** [OSGeo/PROJ-data#92]
This file is not available in the old repo: https://github.com/OSGeo/proj-datumgrid/tree/master/europe

Is it possible to convert the TIFF back to the old format and add it there?

**Comment by kbevers** [comment]
The proj-datumgrid package has been discontinued and is not maintained anymore. 

You can convert the TIFF files to gtx format yourself using `gdal_translate` and add it to your own grid archive.

**Comment by OrangeDog** [comment]
I tried that, but the resulting .gtx doesn't appear to be used. Does it have to have a specific filename or be referenced somewhere?

I guess I'm better off just upgrading, as the .tif does work.

**Comment by kbevers** [comment]
> I guess I'm better off just upgrading, as the .tif does work.

That's the definitely recommended!

If you insist on using PROJ 6 I expect that you need to define the transformation manually as the grids as far as I recall aren't registered in proj.db.
