### ISSUE TITLE
https://cdn.proj.org response headers in case of CORS

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/PROJ-data#95]
PROJ read grid shift, by default , from `https://cdn.proj.org`.
when downloading from this URL, the AWS server set the `Access-Control-Allow-Origin` to `'*'`
but, for reading the `'Range`' header in case of CORS, the '`Access-Control-Expose-Headers`' should also be set to '*'

**Comment by rouault** [comment]
@aharondavid S3 doesn't allow the wildcard value "*". So I've just added "Range".
CC @hobu the new CORS configuration is thus
```json
[
    {
        "AllowedHeaders": [
            "Authorization"
        ],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [
            "Range"
        ],
        "MaxAgeSeconds": 3000
    }
]
```

**Comment by aharondavid** [comment]
Actually, to be more precisely, the headers that used by the function proj_network_get_header_value_cbk_type are:
1. 'Content-Range' 
2. 'Last-Modified'
3. 'ETag'

Can you add them too

**Comment by rouault** [comment]
> Can you add them too

done

**Comment by aharondavid** [comment]
Thanks!

**Comment by aharondavid** [comment]
I think, there is a regression. now I get from the browser `the` following error:
`Access to XMLHttpRequest at 'https://cdn.proj.org/us_nga_egm96_15.tif' from origin 'http://localhost:6931' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by aharondavid** [comment]
I built the PROJ by Emscripten to WebAssembly , so, proj_network_get_header_value_cbk_type is inside `wasm `that is called
from html\js

**Comment by hobu** [comment]
> I built the PROJ by Emscripten to WebAssembly 

OK, this makes more sense. Is there any opportunity for you to contribute back your Emscripten build configuration and usages?

It's a bit dangerous for us to be changing headers on the live production CDN. Especially the ETag one, I think.

**Comment by rouault** [comment]
I've added "Access-Control-Allow-Origin" to the list, but obviously I hardly understand all that stuff.

@hobu Should I just revert all the changes done in ExposeHeaders and restore it to [] ?

**Comment by aharondavid** [comment]
here are a html\js full code example:
you can run it in cmd: `node server.js`
and you will see the CORS error.

**server.js**:
```
const http = require('http');
const fs = require('fs');

const port = 3000;

http.createServer((req, res) => {
		   
	
  const filePath = './testCORS.html';

  fs.readFile(filePath, (err, data) => {
    if (err) {
      res.writeHead(500);
      res.end(`Error: ${err}`);
      return;
    }

    res.writeHead(200, {
      'Content-Type': 'text/html',
      'Access-Control-Allow-Origin': '*'
    });
    res.end(data);
  });
}).listen(port, () => {
  console.log(`Server running on port ${port}`);
});
```
**testCORS.html:**
```
<html>
<head>
  <title>XMLHttpRequest Example</title>
</head>
<body onload="makeRequest()">

  <script>
    function makeRequest() {	
      const xhr = new XMLHttpRequest();
      xhr.open('GET', 'https://cdn.proj.org/us_nga_egm96_15.tif');
      xhr.setRequestHeader('Range', 'bytes=100-199');
      xhr.onreadystatechange = function() {
        if (this.readyState === 4) {
          console.log(`Response status code: ${this.status}`);
          console.log('Response headers:');
          console.log(this.getAllResponseHeaders());
          console.log(`Response body: ${this.responseText}`);
        }
      };

      xhr.send();
    }
  </script>

</body>
</html>
```

**Comment by connormanning** [comment]
Your error is coming from the preflight `OPTIONS` request - not the `GET` itself.  And the reason for that failure is that the `OPTIONS` request is coming back as `403 forbidden`:

<img width="1371" alt="options" src="https://user-images.githubusercontent.com/5015470/220955769-44d02f59-6b35-49b2-8c7a-f5e769b83ddf.png">

So this is not about GET parameters but rather that the preflight is failing so the browser auto-fails the GET.  Maybe OPTIONS needs to be added to AllowedMethods?

**Comment by connormanning** [comment]
It looks like this is from CloudFront rather than S3 directly (right?).  @rouault perhaps make sure that you have GET/HEAD/OPTIONS allowed here (from the "Behaviors" tab):

<img width="471" alt="cloudfront" src="https://user-images.githubusercontent.com/5015470/220957549-ecb2552b-fdf1-46c3-9fd8-e1d78e785fd0.png">

**Comment by rouault** [comment]
I've reverted the CORS configuration of the bucket back to its initial state:
```
[
    {
        "AllowedHeaders": [
            "Authorization"
        ],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [],
        "MaxAgeSeconds": 3000
    }
]
```
and I've changed the CloudFront configuration to @connormanning 's above suggestion

**Comment by connormanning** [comment]
CloudFront changes take 15+ minutes to deploy - give it another 20 or 30 minutes.

**Comment by hobu** [comment]
Configuration seems to be working for me now. Please confirm and we can close.

**Comment by connormanning** [comment]
Works for me now.

**Comment by aharondavid** [comment]
Hi, sorry about delay (I just now come back from weekend).

Now, there is no CORS but the above headers are missing from the response:
1. `'Content-Range' `
2. `'Last-Modified'`
3. `'ETag'`

They are crucial for `proj_network_get_header_value_cbk_type`
As I worte above, I think that the `Access-Control-Expose-Headers` should be set to `'*'`
